core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("website.urls")),
    path("admin/", admin.site.urls),
]

website/urls.py
from django.urls import path

from .views import home, scraping_history, run_manual_scraping

app_name = "website"
urlpatterns = [
    path("", home, name="home"),
    path("scraping-history/", scraping_history, name="scraping_history"),
    path("run-manual-scraping/", run_manual_scraping, name="run_manual_scraping"),
]

website/models.py
from django.db import models

from .common import ScrapingStatuses


class ScrapingHistory(models.Model):
    start_datetime = models.DateTimeField(auto_now_add=True)
    end_datetime = models.DateTimeField(null=True, blank=True)
    status = models.IntegerField(choices=ScrapingStatuses.choices, default=0)

    def __str__(self):
        return str(self.status)


class Article(models.Model):
    title = models.CharField(max_length=500, unique=True)
    subtitle = models.TextField()
    author = models.CharField(max_length=100)
    image_src = models.TextField()
    url = models.TextField()
    published_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    scraping_history = models.ForeignKey(ScrapingHistory, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)

website/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .tasks import scrape_website_manual
from .models import ScrapingHistory, Article


def home(request):
    data = Article.objects.all().order_by("-created_date")
    page = request.GET.get("page", 1)

    page_range = None
    paginator = Paginator(data, 20)
    try:
        page_list = paginator.page(page)
        page_range = paginator.get_elided_page_range(number=page)
    except PageNotAnInteger:
        page_list = paginator.page(1)
        page_range = paginator.get_elided_page_range(number=1)
    except EmptyPage:
        page_list = paginator.page(paginator.num_pages)
    return render(
        request,
        "website/home.html",
        {"page_title": "Home", "articles": page_list, "page_range": page_range},
    )


def scraping_history(request):
    histories = ScrapingHistory.objects.all().order_by("-start_datetime")
    page = request.GET.get("page", 1)

    paginator = Paginator(histories, 10)
    page_range = paginator.get_elided_page_range(number=page)
    try:
        page_list = paginator.page(page)
    except PageNotAnInteger:
        page_list = paginator.page(1)
    except EmptyPage:
        page_list = paginator.page(paginator.num_pages)
    return render(
        request,
        "website/scraping_history.html",
        {
            "histories": page_list,
            "page_range": page_range,
            "page_title": "Scraping History",
        },
    )


def run_manual_scraping(request):
    if request.method == "POST":
        sh = ScrapingHistory(status=1)
        sh.save()
        scrape_website_manual.delay(sh.id)

    return redirect("website:scraping_history")

templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'website/favicon.png' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">
    <title>
      {% block title %}
        Django Web Scraper - {{ page_title|default:"Home" }}
			{% endblock title %}
    </title>
  </head>
  <body>
    {% include "website/navbar.html" %}
    <div class="container-lg">
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'website/script.js' %}" ></script
  </body>
</html>

templates/website/home.html
{% extends 'website/base.html' %}

{% block content %}
  <div class="mt-4 mb-3">
    <h2 class="text-center mb-3">List of Articles</h2>
    {% for article in articles %}
      <section class="card mt-2 mb-2 article-section">
        <a href="{{ article.url }}" target="_blank">
          <div class="card-body article-card-body">
            <div>
              <p class="card-text"><small class="text-muted scraped-date">{{ article.created_date|date }}</small></p>
              <h5 class="card-title">{{ article.title }}</h5>
              <p class="card-text">{{ article.author }}</p>
              <p class="card-text"><small class="text-muted">Published date: {{ article.published_date|date }}</small></p>
            </div>
            <div class="article-card-img-container">
              <img src="{% if article.image_src %}{{ article.image_src }}{% else %}https://via.placeholder.com/112{% endif %}" alt="{{ article.title }}" />
            </div>
          </div>
        </a>
      </section>
    {% empty %}
      <h5 class="no-articles">No articles found</h5>
    {% endfor %}
  </div>
  {% include 'website/pagination.html' with data=articles url_name="website:home" %}
{% endblock content %}

templates/website/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container-lg">
    <a class="navbar-brand" href="{% url 'website:home' %}">Web Scraper</a>
    <a class="scraping-history-link" href="{% url 'website:scraping_history' %}">Scraping History</a>
  </div>  
</nav>

templates/website/pagination.html
{% if data.has_other_pages %}
    <nav aria-label="Page navigation" class="mb-4">
      <ul class="pagination justify-content-center">
        {% if data.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{% url url_name %}?page={{ data.previous_page_number }}">&laquo</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&laquo</a>
          </li>
        {% endif %}
        {% for page_number in page_range|default_if_none:data.paginator.get_elided_page_range %}
          {% if data.number == page_number %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
          {% else %}
            {% if page_number == data.paginator.ELLIPSIS %}
                <li class="page-item"><span class="page-link">{{ page_number }}</span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="{% url url_name %}?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
          {% endif %}
        {% endfor %}
        {% if data.has_next %}
          <li class="page-item">
            <a class="page-link" href="{% url url_name %}?page={{ data.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}

templates/website/scraping_history.html
{% extends 'website/base.html' %}

{% block content %}
  <div class="d-flex justify-content-between mt-3">
    <h1 class="scraping-history-title" id="scraping-history-title">List of Scraping History</h1>
    <form action="{% url 'website:run_manual_scraping' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">Run Manual Scraping</button>
    </form>
  </div>
  <div class="d-flex flex-column align-items-center mt-3">
    <table class="table table-striped table-hover" aria-describedby="scraping-history-title">
      <thead>
        <tr class="table-primary">
          <th scope="col" style="width: 5%">#</th>
          <th scope="col" style="width: 35%">Start</th>
          <th scope="col" style="width: 35%">End</th>
          <th scope="col" style="width: 20%">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for history in histories %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ history.start_datetime }}</td>
            <td>{{ history.end_datetime }}</td>
            {% include 'website/status.html' with status=history.status %}
          </tr>
        {% empty %}
          <tr>
            <td colspan="4" class="no-scraping-history">No scraping history</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include 'website/pagination.html' with data=histories url_name="website:scraping_history" %}
{% endblock content %}

templates/website/status.html
{% if status == 0 %}
  <td>Pending</td>
{% elif status == 1 %}
  <td>In Progress</td>
{% elif status == 2 %}
  <td>Completed</td>
{% else %}
  <td>Failed</td>
{% endif %}